Demo
TotempaaltJ/browser-quiz-project-starter pull request #25
Opened 2021-03-12 18:50 UTC by mahermer88

I know it is a lot of change, but I had to reformat all code.

2021-03-14 09:39 UTC, TotempaaltJ requested changes
Tiny comments

2021-03-14 09:39 UTC, TotempaaltJ commented on public/style.css
> +  background-image: linear-gradient();
What's this for?

2021-03-14 09:39 UTC, TotempaaltJ commented on src/listeners/onload.js
> +import { questionToAdd } from '../handlers/add-Question.js';
`delete-question.js` and `add-question.js` should have lowercase Q's here

2021-03-14 09:39 UTC, TotempaaltJ commented on src/views/render-question.js
> +    button.innerText = value; // add the test of answer
"test" should probably be "text"

2021-03-14 09:39 UTC, TotempaaltJ commented on src/views/render-question.js
> +    hint.target = '_blank'; // make the link open in new tab
The code here is obvious enough that it shouldn't need comments

2021-03-14 09:48 UTC, mahermer88 commented on public/style.css
> +  background-image: linear-gradient();
it is a mistake

2021-03-15 22:06 UTC, TotempaaltJ approved these changes
Looks good!

2021-03-15 22:06 UTC, TotempaaltJ commented on src/handlers/select-answer.js
> +  selectedButton.style.borderColor = 'gold'
Missing a semicolon

2021-03-15 22:15 UTC, merged